// Classes that should be considered stable for Compose
// https://developer.android.com/develop/ui/compose/performance/stability/fix#configuration-file

// Kotlin immutable collections
kotlin.collections.*

// Project domain models
app.web.drjackycv.core.domain.**
